config/routes.rb
Rails.application.routes.draw do
  
  
  authenticated :admin do 
    resources :works do
      put :sort, on: :collection
    end
    get '/work_order', to:'works#work_order', as: 'work_order'
    resources :information do
      resources :press_documents
    end
  end
  
  devise_for :admins, controllers: { sessions: "admin/sessions", registrations: "admin/registrations" }
  
  root 'home#index'

  
  get '/press', to: 'page#press'
  get '/3dgallery', to: 'home#index', as: 'threed'
  get '/work', to: 'page#image_gallery'
  get '/about', to: 'page#about'
  get '/cv', to: 'page#cv'

end

app/models/press_document.rb
class PressDocument < ActiveRecord::Base
  belongs_to :information

  has_attached_file :pdf
  validates_attachment :pdf, :content_type => { :content_type => %w(application/pdf) }
  validates_presence_of :pdf, :name

end

app/controllers/press_documents_controller.rb
class PressDocumentsController < ApplicationController
  before_action :set_press_document, only: [:show, :edit, :update, :destroy]

  # GET /press_documents
  # GET /press_documents.json
  def index
    @press_documents = PressDocument.all
  end

  # GET /press_documents/1
  # GET /press_documents/1.json
  def show
  end

  # GET /press_documents/new
  def new
    @information = Information.find(params[:information_id])
    @press_document = @information.press_documents.new
  end

  # GET /press_documents/1/edit
  def edit
  end

  # POST /press_documents
  # POST /press_documents.json
  def create
    @press_document = PressDocument.new(press_document_params)

    respond_to do |format|
      if @press_document.save
        format.html { redirect_to [@press_document.information,@press_document], notice: 'Press document was successfully created.' }
        format.json { render :show, status: :created, location: @press_document }
      else
        format.html { render :new }
        format.json { render json: @press_document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /press_documents/1
  # PATCH/PUT /press_documents/1.json
  def update
    respond_to do |format|
      if @press_document.update(press_document_params)
        format.html { redirect_to @press_document, notice: 'Press document was successfully updated.' }
        format.json { render :show, status: :ok, location: @press_document }
      else
        format.html { render :edit }
        format.json { render json: @press_document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /press_documents/1
  # DELETE /press_documents/1.json
  def destroy
    @press_document.destroy
    respond_to do |format|
      format.html { redirect_to information_press_documents_url, notice: 'Press document was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_press_document
      @press_document = PressDocument.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def press_document_params
      params.require(:press_document).permit(:pdf, :information_id)
    end
end

app/helpers/press_documents_helper.rb
module PressDocumentsHelper
end

app/views/press_documents/_form.html.erb
<%= form_for [@press_document.information, @press_document] do |f| %>
  <% if @press_document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@press_document.errors.count, "error") %> prohibited this press_document from being saved:</h2>

      <ul>
      <% @press_document.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :pdf %><br>
    <%= f.file_field :pdf %>
  </div>
    <div class="field">
    <%= f.label :pdf %><br>
    <%= f.file_field :pdf %>
    </div>
    <div class="field">
	    <%= f.label :name %><br>
	    <%= f.file_field :name %>
    </div>

    <br>
    Don't edit below this line unless you know what you're doing.
    <br>
  <div class="field">
    <%= f.label :information_id %><br>
    <%= f.text_field :information_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/press_documents/edit.html.erb
<div class="site-wrapper-inner">
  <div class="cover-container">
	  <div class="inner">


<h1>Editing Press Document</h1>

<%= render 'form' %>

<%= link_to 'Show', [@press_document.information, @press_document] %> |
<%= link_to 'Back', information_press_documents_path %>

    </div>
  </div>
</div>

app/views/press_documents/index.html.erb
<div class="site-wrapper-inner">
  <div class="cover-container">
	  <div class="inner">


<p id="notice"><%= notice %></p>

<h1>Listing Press Documents</h1>
<div class='table-responsive'>
<table class='table'>
  <thead>
    <tr>
      <th>Name</th>
      <th>Download</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @press_documents.each do |press_document| %>
      <tr>
        <td><%= press_document.name %></td>
        <td><%= link_to 'download', press_document.pdf.url %></td>
        <td><%= link_to 'Show', [press_document.information, press_document] %></td>
        <td><%= link_to 'Edit', edit_information_press_document_path(press_document.information, press_document) %></td>
        <td><%= link_to 'Destroy', [press_document.information, press_document], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

<%= link_to 'New Press document', new_information_press_document_path %>

	  </div>
  </div>
</div>

app/views/press_documents/new.html.erb
<div class="site-wrapper-inner">
  <div class="cover-container">
    <div class="inner">


<h1>New Press Document</h1>

<%= render 'form' %>

<%= link_to 'Back', information_press_documents_path %>

    </div>
  </div>
</div>

app/views/press_documents/show.html.erb
<div class="site-wrapper-inner">
  <div class="cover-container">
	  <div class="inner">
		  
<p id="notice"><%= notice %></p>

<p>
  <strong>Pdf:</strong>
  <%= @press_document.pdf.url %>
</p>

<p>
  <strong>Name:</strong>
  <%= @press_document.name %>
</p>


<p>
  <strong>Information:</strong>
  <%= @press_document.information %>
</p>

<%= link_to 'Edit', edit_information_press_document_path(@press_document.information,@press_document) %> |
<%= link_to 'Back', information_press_documents_path %>


    </div>
  </div>
</div>