config/routes.rb
Rails.application.routes.draw do
  
  
  authenticated :admin do 
    resources :works do
      put :sort, on: :collection
    end
    get '/work_order', to:'works#work_order', as: 'work_order'
    resources :information do
      resources :press_documents
    end
  end
  
  devise_for :admins, controllers: { sessions: "admin/sessions", registrations: "admin/registrations" }
  
  root 'home#index'

  
  get '/press', to: 'page#press'
  get '/3dgallery', to: 'home#index', as: 'threed'
  get '/work', to: 'page#image_gallery'
  get '/about', to: 'page#about'
  get '/cv', to: 'page#cv'

end

app/models/work.rb
class Work < ActiveRecord::Base
  after_destroy :reorder_works

  validates_presence_of :image, :name, :year, :message => "missing, fill in ya shit dummy."
  
  has_attached_file :image, styles: lambda { |a|
    a.instance.is_image? ? { medium: "1000x1000>", thumb: "300x300>", tiny_thumb: "50x50>" } :
      { :medium => { :geometry => "640x480>", :format => 'mp4' },
        :thumb => { :geometry => "300x300>", :format => 'jpg', :time => 2},
        :tiny_thumb => {:geometry => "50x50>", :format => 'jpg', :time => 2}}},
                    :processors => lambda { |a| a.is_video? ? [:transcoder] : [ :thumbnail ] }
  
  validates_attachment_content_type :image,
                       content_type: ['image/png', 'image/jpeg', 'image/jpg', 'image/gif'],
                       message:      "Different error message",
                       if:           :is_image?


  validates_attachment_content_type :image,
                       content_type: ['video/mp4'],
                       message:      "Sorry, right now we only support MP4 video",
                       if:           :is_video?

  def self.ordered_works
    Work.all.order(:order)
  end

  def is_video?
    image.instance.image_content_type =~ %r(video)
  end

  def is_image?
    image.instance.image_content_type =~ %r(image)
  end


  private

  def reorder_works
    works = Work.ordered_works
    works.each_with_index do |work, i|
      work.update({order: i+1})
    end
  end

  
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :set_work, only: [:show, :edit, :update, :destroy]

  # GET /works
  # GET /works.json
  def index
    @works = Work.ordered_works
  end

  # GET /works/1
  # GET /works/1.json
  def show
  end

  # GET /works/new
  def new
    @work = Work.new
  end

  # GET /works/1/edit
  def edit
  end

  # POST /works
  # POST /works.json
  def create
    mod_work_params = work_params.merge({ "order" => Work.all.size + 1})
    @work = Work.new(mod_work_params)

    respond_to do |format|
      if @work.save
        format.html { redirect_to @work, notice: 'Work was successfully created.' }
        format.json { render :show, status: :created, location: @work }
      else
        format.html { render :new }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /works/1
  # PATCH/PUT /works/1.json
  def update
    respond_to do |format|
      if @work.update(work_params)
        format.html { redirect_to @work, notice: 'Work was successfully updated.' }
        format.json { render :show, status: :ok, location: @work }
      else
        format.html { render :edit }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /works/1
  # DELETE /works/1.json
  def destroy
    @work.destroy
    respond_to do |format|
      format.html { redirect_to works_url, notice: 'Work was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  # GET /works/work_order
  def work_order
    @works = Work.ordered_works
  end

  # PUT /works/sort
  def sort
    params[:order].each do |key,value|
      Work.find(value[:id]).update_attribute(:order,value[:position])
    end
    render :nothing => true
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work
      @work = Work.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def work_params
      params.require(:work).permit(:name, :year, :image)
    end
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/works/_form.html.erb
<%= form_for(@work) do |f| %>
  <% if @work.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@work.errors.count, "error") %> prohibited this work from being saved:</h2>

      <ul>
      <% @work.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.text_field :year %>
  </div>

  <%= f.file_field :image %>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/works/edit.html.erb
<div class="site-wrapper-inner">
  <div class="cover-container">
    <div class="inner">


<h1>Editing Work</h1>

<%= render 'form' %>

<%= link_to 'Show', @work %> |
<%= link_to 'Back', works_path %>


    </div>
  </div>
</div>

app/views/works/index.html.erb
<div class="site-wrapper-inner">
  <div class="cover-container">
    <div class="inner">


<p id="notice"><%= notice %></p>

<h1>Listing Works</h1>

<div class="table-responsive listing">
<table class="table">
  <thead>
	  <tr>
		  <th>Image</th>
      <th>Name</th>
      <th>Year</th>
      <th>Order</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody >
    <% @works.each do |work| %>
	    <tr>
		    <td><%= image_tag work.image.url(:tiny_thumb) %></td>
        <td><%= work.name %></td>
        <td><%= work.year %></td>
        <td><%= work.order %></td>
        <td><%= link_to 'Show', work %></td>
        <td><%= link_to 'Edit', edit_work_path(work) %></td>
        <td><%= link_to 'Destroy', work, method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

<%= link_to 'New Work', new_work_path %><br>
<%= link_to 'Edit Work Order', work_order_path %>

    </div>
  </div>
</div>

app/views/works/new.html.erb
<div class="site-wrapper-inner">
  <div class="cover-container">
    <div class="inner">


<h1>New Work</h1>

<%= render 'form' %>

<%= link_to 'Back', works_path %>


    </div>
  </div>
</div>

app/views/works/show.html.erb
<div class="site-wrapper-inner">
  <div class="cover-container">
    <div class="inner">


	    <p id="notice"><%= notice %></p>

	    <p><strong>Image:</strong>
		    <%= image_tag @work.image.url(:thumb)  %>
	    </p>
	    

<p>
  <strong>Name:</strong>
  <%= @work.name %>
</p>

<p>
  <strong>Year:</strong>
  <%= @work.year %>
</p>

<p>
  <strong>Order:</strong>
  <%= @work.order %>
</p>

<%= link_to 'Edit', edit_work_path(@work) %> |
<%= link_to 'Back', works_path %>

    </div>
  </div>
</div>

app/views/works/work_order.html.erb
<div class="site-wrapper-inner">
  <div class="cover-container">
    <div class="inner">
      <h1>Drag Works Into Order</h1>
      <br>
      <div id="listWithHandle" class="list-group sortable" style="overflow-y: scroll; height: 300px;">
	<% @works.each do |work| %>
	<div class="list-group-item" data-id="<%= work.id %>">
	  <span class="glyphicon glyphicon-move" aria-hidden="true"></span>
	  &nbsp;&nbsp;&nbsp; 
	  <%= image_tag work.image.url(:tiny_thumb)  %>
	  &nbsp;&nbsp;&nbsp;&nbsp; &nbsp; &nbsp; 
	  <%= work.name  %> //
	  <%= work.year %>

	</div>
	<% end %>
      </div>
      <br>
      <%= link_to "Work Dashboard", works_path %>
      
    </div>
  </div>
</div>

<script>
var ready, set_positions;

set_positions = function(){
	// loop through and give each task a data-pos
	// attribute that holds its position in the DOM
	$('.list-group-item').each(function(i){
		$(this).attr("data-pos",i+1);
	});
}

ready = function(){

	// call set_positions function
	set_positions();

	$('.sortable').sortable();

	$('.sortable').sortable().bind('sortupdate', function(e, ui) {
		// array to store new order
		updated_order = []
		// set the updated positions
		set_positions();

		// populate the updated_order array with the new task positions
		$('.list-group-item').each(function(i){
			updated_order.push({ id: $(this).data("id"), position: i+1 });
		});

		// send the updated order via ajax
		$.ajax({
			type: "PUT",
			url: '/works/sort',
			data: { order: updated_order }
		});
	});
}

$(document).ready(ready);

</script>