config/routes.rb
Rails.application.routes.draw do
  
  
  authenticated :admin do 
    resources :works do
      put :sort, on: :collection
    end
    get '/work_order', to:'works#work_order', as: 'work_order'
    resources :information do
      resources :press_documents
    end
  end
  
  devise_for :admins, controllers: { sessions: "admin/sessions", registrations: "admin/registrations" }
  
  root 'home#index'

  
  get '/press', to: 'page#press'
  get '/3dgallery', to: 'home#index', as: 'threed'
  get '/work', to: 'page#image_gallery'
  get '/about', to: 'page#about'
  get '/cv', to: 'page#cv'

end

app/models/information.rb
class Information < ActiveRecord::Base
  has_many :press_documents
  accepts_nested_attributes_for :press_documents
  
  has_attached_file :document
  validates_attachment :document, :content_type => { :content_type => %w(application/pdf) }
  validates_presence_of :document, :about, :version, :press

end

app/controllers/information_controller.rb
class InformationController < ApplicationController
  before_action :set_information, only: [:show, :edit, :update, :destroy]
    
  # GET /information
  # GET /information.json
  def index
    @information = Information.all
  end

  # GET /information/1
  # GET /information/1.json
  def show
  end

  # GET /information/new
  def new
    @information = Information.new
    @information.press_documents.build
  end

  # GET /information/1/edit
  def edit
  end

  # POST /information
  # POST /information.json
  def create
    @information = Information.new(information_params)
    respond_to do |format|
      if @information.save
        format.html { redirect_to @information, notice: 'Information was successfully created.' }
        format.json { render :show, status: :created, location: @information }
      else
        format.html { render :new }
        format.json { render json: @information.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /information/1
  # PATCH/PUT /information/1.json
  def update
    respond_to do |format|
      if @information.update(information_params)
        format.html { redirect_to @information, notice: 'Information was successfully updated.' }
        format.json { render :show, status: :ok, location: @information }
      else
        format.html { render :edit }
        format.json { render json: @information.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /information/1
  # DELETE /information/1.json
  def destroy
    @information.destroy
    respond_to do |format|
      format.html { redirect_to information_index_url, notice: 'Information was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_information
      @information = Information.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def information_params
      params.require(:information).permit(:about, :version, :document, :press, :press_documents, :pdf, press_documents_attributes: [:pdf, :name])
    end
end

app/helpers/information_helper.rb
module InformationHelper
end

app/views/information/_form.html.erb
<%= form_for(@information) do |f| %>
  <% if @information.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@information.errors.count, "error") %> prohibited this information from being saved:</h2>

      <ul>
      <% @information.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
    <%= f.label :version %><br>
    <%= f.text_field :version %>
    </div>


    <div class="field">
    <%= f.label :about %><br>
    <%= f.text_area :about %>
    </div>

    <div class="field">
    <%= f.label :press %><br>
    <%= f.text_area :press %>
    </div>


    <div class="field">
	    <%= f.label :document %><br>
	    <%= f.file_field :document %>
    </div>
    <br>
    <div class="field">
	    <%= f.fields_for :press_documents do |c| %>
		    <%= c.label :pdf %><br>
		    <%= c.file_field :pdf %><br>
		    <%= c.text_field :name %>

	    <% end %>
    </div>
    <br>

  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/information/edit.html.erb
<div class="site-wrapper-inner">
  <div class="cover-container">
    <div class="inner">


<h1>Editing Information</h1>

<%= render 'form' %>

<%= link_to 'Show', @information %> |
<%= link_to 'Back', information_index_path %>


    </div>
  </div>
</div>

app/views/information/index.html.erb
<div class="site-wrapper-inner">
  <div class="cover-container">
    <div class="inner">
<p id="notice"><%= notice %></p>

<h1>Listing Information</h1>
<div class="table-responsive" style="overflow-y: scroll; height: 300px;">
<table class="table" >
  <thead>
	  <tr>
		  <th>Version</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @information.reverse_each do |information| %>
	    <tr>
		    <td><%= information.version %></td>
        <td><%= link_to 'Show', information %></td>
        <td><%= link_to 'Edit', edit_information_path(information) %></td>
        <td><%= link_to 'Destroy', information, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

<%= link_to 'New Information', new_information_path %>


    </div>
  </div>
</div>

app/views/information/new.html.erb
<div class="site-wrapper-inner">
  <div class="cover-container">
    <div class="inner">


	    <h1>New Information</h1>
	    <div style="overflow-y: scroll; height: 400px; border-width: 1px; border-style: solid; padding: 5px;">
<%= render 'form' %>

<%= link_to 'Back', information_index_path %>
		    </div>

    </div>
  </div>
</div>

app/views/information/show.html.erb
<div class="site-wrapper-inner">
  <div class="cover-container">
    <div class="inner">

<p id="notice"><%= notice %></p>

<p>
  <strong>Version:</strong>
  <%= @information.version %>
</p>

<p>
  <strong>About Text:</strong>
  <%= @information.about %>
</p>

<p>
  <strong>Press Text:</strong>
  <%= @information.press %>
</p>


<p>
	<strong>PDFs: </strong>
	<%= link_to "PDFs", information_press_documents_path(@information) %>
</p>


<p>
  <strong>CV Download:</strong>
  <%= link_to 'Click for Download', @information.document.url %>
</p>


<%= link_to 'Edit', edit_information_path(@information) %> |
<%= link_to 'Back', information_index_path %>


    </div>
  </div>
</div>