config/routes.rb
Rails.application.routes.draw do
  
  
  authenticated :admin do 
    resources :works do
      put :sort, on: :collection
    end
    get '/work_order', to:'works#work_order', as: 'work_order'
    resources :information do
      resources :press_documents
    end
  end
  
  devise_for :admins, controllers: { sessions: "admin/sessions", registrations: "admin/registrations" }
  
  root 'home#index'

  
  get '/press', to: 'page#press'
  get '/3dgallery', to: 'home#index', as: 'threed'
  get '/work', to: 'page#image_gallery'
  get '/about', to: 'page#about'
  get '/cv', to: 'page#cv'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Martha Friedman</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>  
  </head>
  <body>
    <div id="container">
      <header>
	      <ul>
	        <li><%= link_to("MARTHA FRIEDMAN", threed_path, class: "title menu-styles") %>
	          <ul>
	            <li><a class="menu-styles bold" href="/work" style="padding-top:80px;">Image Gallery</a></li>
	            <!-- <li><a class="menu-styles bold" href="/about">About</a></li> -->
	            <li><%= link_to "CV", @cv, class: 'menu-styles bold', target: '_blank' %></li>
	            <li><a class="menu-styles bold" href="/press">News</a></li>
	            <% if admin_signed_in? %>
		          <li><%= link_to "work dashboard", works_path, class: 'menu-styles bold' %></li>
		          <li><%= link_to "information dashboard", information_index_path, class: 'menu-styles bold' %></li>
		          <li><%= link_to "edit profile", edit_admin_registration_path, class: 'menu-styles bold' %></li>
		          <li><%= link_to "sign out", destroy_admin_session_path, method: :delete, class: 'menu-styles bold' %></li>
	            <% end %>
	          </ul>
	        </li>
	      </ul>
      </header>

      <% if browser.device.mobile? %>
      <style>
        header ul ul {
        display: block;
        font-size: 20px;
        }
      </style>
      <% end %>

      <!-- if the scene is running already, kill it. very important script,
           keeps the scene from rendering when it's not actually being displayed -->
      <script>
        if (scene) { scene = null; }
      </script>


      <%= yield %>

      <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-77376627-1', 'auto');
        ga('send', 'pageview');

      </script>
    </div>
  </body>
</html>